Add row button to monbile row
Flexberry/ember-flexberry pull request #1014
Opened 2020-03-23 09:11 UTC by PashaMasalkin

2020-03-24 10:40 UTC, KollegOFF requested changes

2020-03-24 10:40 UTC, KollegOFF commented on app/templates/mobile/components/object-list-view-row.hbs
>      style="padding-left:{{hierarchicalIndent}}px;">
```suggestion
      {{action "onRowClick" record (hash column=columns) preventDefault=false}}
      style="padding-left:{{hierarchicalIndent}}px;">
```

2020-03-24 10:40 UTC, KollegOFF commented on app/templates/mobile/components/object-list-view-row.hbs
> +          disabled={{readonly}}
Here you also need to check `record.rowConfig.canBeDeleted`.

2020-03-24 12:50 UTC, PashaMasalkin commented on addon/styles/themes/blue-sky/elements/icon.overrides
> +.object-list-view-row-delete-button.mobile i.minus.icon {
And in the non-mobile version?

2020-03-24 16:33 UTC, KollegOFF commented on addon/styles/themes/blue-sky/elements/icon.overrides
> +.object-list-view-row-delete-button.mobile i.minus.icon {
I thought that these are new classes, let’s leave them since they are already in use.

2020-03-25 05:41 UTC, KollegOFF requested changes

2020-03-25 05:41 UTC, KollegOFF commented on app/templates/mobile/components/object-list-view-row.hbs
> +          disabled={{readonly}}
For the attribute `disabled`.

2020-03-25 05:41 UTC, KollegOFF commented on app/templates/mobile/components/object-list-view-row.hbs
>      style="padding-left:{{hierarchicalIndent}}px;">
Indentation is not enough for these lines.

2020-03-25 10:56 UTC, KollegOFF approved these changes

2020-03-25 11:30 UTC, KollegOFF approved these changes

2020-03-26 16:17 UTC, merged