Add selected menu for mobile
Flexberry/ember-flexberry pull request #1018
Opened 2020-03-24 12:54 UTC by s-andrey

#997

2020-03-25 13:37 UTC, KollegOFF requested changes

2020-03-25 13:37 UTC, KollegOFF commented on addon/components/object-list-view.js
> +  selectedMobileMenu: false,
- `_showSelectionMenu`
- private
- computed (`selectedRecords.length`, `allSelect`, `allSelectAtPage`, ...)

2020-03-25 13:37 UTC, KollegOFF commented on addon/components/object-list-view.js
> +  selectedCountMobileMenu: 0,
- private
- computed (`selectedRecords.length` or `recordsTotalCount` from `flexberry-objectlistview` component)

2020-03-25 13:37 UTC, KollegOFF commented on addon/components/object-list-view.js
> +    clearSelectedRecordsMobile() {
Ignores the `allSelect` property.

2020-03-25 13:37 UTC, KollegOFF commented on addon/components/object-list-view.js
> +    deleteSelectedRowMobile() {
Instead of adding the `...Mobile` suffix everywhere, move the changes to `components/mobile/object-list-view.js`.

2020-03-25 13:37 UTC, KollegOFF commented on addon/components/object-list-view.js
> +      {
Formatting.
```suggestion
      if (!this.get('allSelect')) {
```

2020-03-25 13:37 UTC, KollegOFF commented on app/templates/mobile/components/object-list-view.hbs
> +      {{#if checkRowsSettingsItems}}
What for this check?

2020-03-25 13:37 UTC, KollegOFF commented on app/templates/mobile/components/object-list-view.hbs
> +  {{#if readonly}}
Use `disabled={{readonly}}` instead of the block form.

2020-03-26 05:32 UTC, s-andrey commented on addon/components/object-list-view.js
> +  selectedMobileMenu: false,
3 пункт это добавить в условие computed-а _showSelectionMenu?

2020-03-26 05:33 UTC, s-andrey commented on addon/components/object-list-view.js
> +  selectedCountMobileMenu: 0,
Тоже не понятен коммент с computed

2020-03-26 05:34 UTC, s-andrey commented on app/templates/mobile/components/object-list-view.hbs
> +  {{#if readonly}}
Так не сработает.... у disabled нет значений (http://htmlbook.ru/html/input/disabled)
PS этот фрагмент кода был взят из olv-toolbar там так же

2020-03-26 05:38 UTC, s-andrey commented on addon/components/object-list-view.js
> +  selectedMobileMenu: false,
Заменить это свойство на computed не получится тк будет зацикливание и бесконечный рендер

2020-03-26 05:38 UTC, s-andrey commented on addon/components/object-list-view.js
> +  selectedCountMobileMenu: 0,
Заменить это свойство на computed не получится тк будет зацикливание и бесконечный рендер

2020-03-26 06:49 UTC, KollegOFF commented on app/templates/mobile/components/object-list-view.hbs
> +  {{#if readonly}}
https://guides.emberjs.com/v3.1.0/templates/binding-element-attributes/

2020-03-29 16:49 UTC, KollegOFF requested changes

2020-03-29 16:49 UTC, KollegOFF commented on addon/components/mobile/object-list-view.js
> +    return this.get('selectedRecords.length') > 0 || this.get('allSelect') || this.get('allSelectAtPage');
```suggestion
  _selectedMobileMenu: computed('selectedRecords.length', 'allSelect', function() {
    return this.get('selectedRecords.length') > 0 || this.get('allSelect');
```

2020-03-29 16:49 UTC, KollegOFF commented on addon/components/mobile/object-list-view.js
> +  _selectedCountMobileMenu: computed('selectedRecords.@each', 'allSelect', function() {
```suggestion
  _selectedCountMobileMenu: computed('selectedRecords.length', 'allSelect', function() {
```

2020-03-29 16:49 UTC, KollegOFF commented on addon/components/mobile/object-list-view.js
> +        return;
https://github.com/Flexberry/ember-flexberry/blob/aaa85e729918775e3b0cd51a443cbcef9e0604fe/addon/components/object-list-view.js#L1160-L1166

2020-03-30 12:51 UTC, merged