Implemented flexberry-tabs
Flexberry/ember-flexberry pull request #1159
Opened 2020-08-07 13:48 UTC by dpavloff

- Added ability to scroll tabs with mousewheel or by dragging the tabs;
- In case tabs overflow its parent container, a dropdown appears, from which another tab can be chosen without scrolling;
- Implemented scrolling with mousewheel, ability to select new tab from dropdown;

2020-09-21 16:42 UTC, KollegOFF reviewed
На самом деле есть необходимость реализовывать прокрутку на JS?
Можно же обычной браузерной прокруткой обойтись, она сейчас практически везде стилизуется, а где нет, там и не надо, мне кажется.

2020-09-22 06:05 UTC, dpavloff commented
Прокрутка была реализована таким образом, чтобы не требовалось зажимать shift при прокрутке. Решил, что это будет более удобным и интуитивным для пользователя решением.

2020-09-23 07:43 UTC, KollegOFF commented
Судя по описанию задачи из ТФС, зажимать `shift` как раз требуется, и мне кажется что, это поведение по умолчанию.
Нужно обсудить допустимость использования прокрутки, с её стилизацией и без.

2020-10-01 09:42 UTC, lulzforme commented
@KollegOFF когда писали постановку, то упор делался на ускорение разработки данного компонента. @dpavloff реализовал всё так как задумывается в макете, так что я не вижу проблем с прокруткой. Плюс такая прокрутка потом поможет нам с внедрением прокрутки в мобильную версию.

2021-01-19 05:47 UTC, pepelyaeva commented
https://github.com/Flexberry/ember-flexberry-themes/pull/89

2021-02-02 04:56 UTC, pepelyaeva requested changes

2021-02-02 04:56 UTC, pepelyaeva commented on addon/styles/themes/default/modules/tab.overrides
> +  float: none;
Надо все стили перенести в blue-sky

2021-02-04 12:00 UTC, Nasutya commented
Созданный пример не открывается, в консоли ошибка:
TypeError: Cannot define property __ember_meta__, object is not extensible
    at Function.defineProperty (<anonymous>)
    at setMeta (ember.debug.js:18845)
    at Object.meta (ember.debug.js:18884)
    at addChainWatcher (ember.debug.js:14601)
    at new ChainNode (ember.debug.js:14649)
    at ChainNode.chain (ember.debug.js:14784)
    at ChainNode.chain (ember.debug.js:14793)
    at ChainNode.add (ember.debug.js:14745)
    at Object.watchPath (ember.debug.js:23562)
    at Object.watch (ember.debug.js:23614)

2023-02-13 08:34 UTC, pepelyaeva commented
Нужно исправить под 3 версию

2023-04-18 04:37 UTC, neroslovegor commented
ПР с документацией по flexberry-tab-bar: https://github.com/Flexberry/flexberry.github.io/pull/164

2023-04-18 12:34 UTC, DubrovinPavel commented on tests/integration/components/flexberry-tab-bar-test.js
> +test('it renders items', function(assert) {
А не получится этот тест объединить с 2 следующими? У них вроде рендерится одно и то же и в результате много повторения

2023-04-18 12:37 UTC, pepelyaeva commented on tests/dummy/app/routes/components-examples/flexberry-tab-bar/settings-example.js
> +});
import Route from '@ember/routing/route';

export default Route.extend({
});

2023-04-18 12:38 UTC, pepelyaeva commented on tests/dummy/app/controllers/components-examples/flexberry-tab-bar/settings-example.js
> +import Ember from 'ember';
import Controller from '@ember/controller';

2023-04-18 12:38 UTC, pepelyaeva commented on tests/dummy/app/controllers/components-examples/flexberry-tab-bar/settings-example.js
> +export default Ember.Controller.extend({
export default Controller.extend({

2023-04-18 12:42 UTC, pepelyaeva commented on addon/styles/themes/blue-sky/modules/tab.overrides
Этот файл нужно удалить

2023-04-18 12:42 UTC, pepelyaeva commented on addon/styles/themes/blue-sky/modules/tab.variables
Этот файл нужно удалить

2023-04-19 07:40 UTC, neroslovegor commented on tests/integration/components/flexberry-tab-bar-test.js
> +test('it renders items', function(assert) {
Объединил 2 последних теста с переходам по вкладкам через меню и выпадающий список.

2023-04-19 09:01 UTC, DubrovinPavel commented on addon/components/flexberry-tab-bar.js
> +    var pY = 0;
Заменить на let/const

2023-04-19 09:02 UTC, DubrovinPavel commented on addon/components/flexberry-tab-bar.js
> +        var direction = x > 0 ? 1 : -1;
Заменить на let/const

2023-04-19 09:09 UTC, DubrovinPavel commented on tests/integration/components/flexberry-tab-bar-test.js
> +    assert.strictEqual($item.attr('data-tab'), 'tab' + new Number(i + 1), 'Component\'s item\'s сaptions matches the array');
Sonar на эти Number еще ругается, я с ним согласен в принципе. МОжно же что-то вроде `tab${i + 1}` сделать

2023-04-19 10:07 UTC, DubrovinPavel approved these changes

2023-04-19 10:10 UTC, pepelyaeva approved these changes

2023-04-19 10:11 UTC, merged