Added hasShadow and hasBorder properties for flexberry-toggler
Flexberry/ember-flexberry pull request #1176
Opened 2020-09-04 13:47 UTC by dpavloff

2020-09-21 16:43 UTC, KollegOFF reviewed
Почему в эту версию?

2020-09-22 06:03 UTC, dpavloff commented
@KollegOFF, доработки по этой задаче касаются только версии с новой темой. Не получиться замерджить без введения аналогичных изменений в вторую версию?

2020-09-23 07:14 UTC, KollegOFF commented
Получиться то получиться, но не хочется. Доработки не большие, не думаю что будет проблема сделать их для всех версий.

2020-09-23 07:28 UTC, KollegOFF requested changes
Нужно [добавить тест](https://github.com/Flexberry/ember-flexberry/blob/5eeee424c5b07f9c64b4cba60b01d89fd7e26623/tests/integration/components/flexberry-toggler-test.js) для этих свойств.

2020-09-23 07:28 UTC, KollegOFF commented on addon/components/flexberry-toggler.js
> +  hasShadow: false,
Я не спец в английском, но думаю что, в этих свойствах, `has` лучше заменить на `show`, или даже просто убрать.

2020-09-23 07:28 UTC, KollegOFF commented on addon/components/flexberry-toggler.js
> +  classNameBindings: ['hasBorder:toggler-has-border', 'hasShadow:toggler-has-shadow'],
У нас нет правил по именованию классов, но кажется что они немного перегруженные.

2020-09-25 14:41 UTC, dpavloff commented on addon/components/flexberry-toggler.js
> +  classNameBindings: ['hasBorder:toggler-has-border', 'hasShadow:toggler-has-shadow'],
Поменял на 'has-border' и 'has-shadow' соответственно.

2020-09-25 14:43 UTC, dpavloff commented on addon/components/flexberry-toggler.js
> +  hasShadow: false,
Хм, недавно познакомился с фреймворком bulma (довольно классным, кстати!), там не гнушаются использовать has. Как мне кажется, для именования CSS классов глагол 'has' выглядит довольно интуитивно.

2020-10-02 08:28 UTC, KollegOFF commented
#1211.

2020-10-02 08:28 UTC, closed without merging