#1071 flexberry-lookup in a single .hbs now
Flexberry/ember-flexberry pull request #1206
Opened 2020-09-21 11:11 UTC by leoleopon

2020-09-23 09:09 UTC, KollegOFF requested changes
Нужно добавить проверку и бросать исключение, при использовании компонента в блочной форме вместе со свойствами `autocomplete` или `dropdown`, и тест на это.
Пусть это будет костыль, не думаю что это самая большая проблема.

2020-09-23 09:09 UTC, KollegOFF commented on app/templates/components/flexberry-lookup.hbs
> +  {{#if autocomplete}}
Объедини это условие.

2020-09-23 09:09 UTC, KollegOFF commented on tests/dummy/app/templates/components-examples/flexberry-lookup/lookup-block-form-example.hbs
> -    <li>{{t "forms.components-examples.flexberry-lookup.lookup-block-form-example.paragraph3"}}</li>
Неиспользуемые сообщения для локализации можно удалить.

2020-09-25 06:54 UTC, leoleopon commented on app/templates/components/flexberry-lookup.hbs
>    <div class="ui fluid action input {{if readonly "disabled"}}">
Имеется ввиду добавлять, если НЕ используется в блочной форме (раньше в не-мобильном шаблоне добавлялось)?

2020-09-25 07:08 UTC, KollegOFF commented on app/templates/components/flexberry-lookup.hbs
>    <div class="ui fluid action input {{if readonly "disabled"}}">
Да, я именно это имел ввиду.

2020-09-29 09:21 UTC, leoleopon commented on tests/dummy/app/templates/components-examples/flexberry-lookup/lookup-block-form-example.hbs
> -    <li>{{t "forms.components-examples.flexberry-lookup.lookup-block-form-example.paragraph3"}}</li>
Поправил.

2020-09-29 09:22 UTC, leoleopon commented on app/templates/components/flexberry-lookup.hbs
> +        class="ui transparent {{if (or readonly isBlocked) " disabled"}} {{if (or modalIsBeforeToShow modalIsStartToShow) " loading"}} icon input ">
Поправил.

2020-09-29 09:23 UTC, leoleopon commented on app/templates/components/flexberry-lookup.hbs
> +      </div>
Поправил.

2020-09-29 09:23 UTC, leoleopon commented on app/templates/components/flexberry-lookup.hbs
>      </button>
Поправил.

2020-09-29 09:24 UTC, leoleopon commented on app/templates/components/flexberry-lookup.hbs
> +  {{#if autocomplete}}
Поправил.

2020-09-29 09:24 UTC, leoleopon commented on app/templates/components/flexberry-lookup.hbs
>    <div class="ui fluid action input {{if readonly "disabled"}}">
Поправил.

2020-09-30 07:31 UTC, KollegOFF commented on addon/components/flexberry-lookup.js
> +    Triggered by the component template if the component has a block form definition.
```suggestion
    Triggered by the component template if the component has a block form definition.

    @private
    @property _hasBlockSetter
```

2020-09-30 07:31 UTC, KollegOFF commented on app/templates/components/flexberry-lookup.hbs
> +  <div data-test-lookup class="ui {{if (not hasBlock) "fluid"}} action input {{if (and readonly (not hasBlock)) "disabled"}}">
```suggestion
  <div data-test-lookup class="ui {{unless hasBlock "fluid"}} action input {{if (and readonly (not hasBlock)) "disabled"}}">
```

2020-10-02 08:44 UTC, leoleopon commented on addon/components/flexberry-lookup.js
> +    Triggered by the component template if the component has a block form definition.
Поправил.

2020-10-02 08:45 UTC, leoleopon commented on app/templates/components/flexberry-lookup.hbs
> +  <div data-test-lookup class="ui {{if (not hasBlock) "fluid"}} action input {{if (and readonly (not hasBlock)) "disabled"}}">
Поправил.

2020-10-02 11:23 UTC, KollegOFF approved these changes

2020-10-02 11:26 UTC, merged