Implemented component flexberrry-sitemap-searchbar
Flexberry/ember-flexberry pull request #1208
Opened 2020-09-25 10:11 UTC by dpavloff

This component can be integrated in any ember app created with ember-flexberry. It allows sitemap search using recursive algorithm. 

Documentation for structure of sitemap object is WIP.

2020-10-01 06:25 UTC, KollegOFF submitted a review, later dismissed
Нужны тесты.

2020-10-01 06:25 UTC, KollegOFF commented on addon/components/flexberry-sitemap-searchbar.js
> +    $sitemapSearch.addEventListener('input', (e) => {
Это нужно делать через экшены, и их привязку к элементам в шаблоне.

2020-10-01 06:25 UTC, KollegOFF commented on addon/components/flexberry-sitemap-searchbar.js
> +      if ((query === null || query === 'undefined' || query === '')) {
Слишком много скобок, и проверок, может просто `if (query) { /* ... */ } else { /* ... */ }`?

2020-10-01 06:25 UTC, KollegOFF commented on addon/components/flexberry-sitemap-searchbar.js
> +      }
Это нужно делать через [`Ember.run.debounce`](https://api.emberjs.com/ember/2.4/namespaces/Ember.run/methods/debounce?anchor=debounce):
```js
Ember.run.debounce(this, this._method, 200);
```

2020-10-01 06:25 UTC, KollegOFF commented on app/templates/components/flexberry-sitemap-searchbar.hbs
> +  <div id="results-list">
Не нужно использовать айдишники для элементов, для стилей нужно использовать классы, для поиска элементов в контексте компонента `this.$('selector')`.
Текст для `placeholder` нужно вынести в локализацию.

2020-10-01 06:25 UTC, KollegOFF commented on app/templates/components/flexberry-sitemap-searchbar.hbs
> +    {{/searchbar-node}}
Не нужно писать компонент в блочной форме, если она не используется.
Классы может через `classNames` описать?

2020-10-01 06:25 UTC, KollegOFF commented on app/templates/components/searchbar-node.hbs
> +  {{/link-to}}
Нужно использовать `t` хелпер для вывода локализованных значений.
Для `title` у ссылки `node.title`, для содержимого `node.caption`.

2020-10-01 06:25 UTC, KollegOFF commented on app/templates/sitemap.hbs
> +treeContent=model.nodes}}
Не нужно добавлять компонент сразу в этот шаблон, лучше добавить его где то здесь:
https://github.com/Flexberry/ember-flexberry/blob/d05d50a6226f580e04db8d2598d2d820db392113/tests/dummy/app/templates/application.hbs#L13-L19

2020-10-01 06:47 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +  treeContent: Ember.A(),
Правда, так будет лучше называться. Поменял на sitemap. Начальное значение установил как null.

2020-10-01 06:47 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +  results: Ember.A(),
Заменил на null, сделал приватным.

2020-10-01 06:49 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +  _searchTree(regexQuery, currentTree) {
Я выбрал регулярное выражение, чтобы в будущем было проще реализовать подсвечивание попадаемых строк. Мне кажется, что такое решение будет очень наглядно и полезно.

2020-10-01 06:50 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +      } else if (this._elementHasChildren(element)) {
Не совсем понял, зачем нужна копия `element`'a?

2020-10-01 06:58 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +          resultTree.push(newElement);
Отличная идея, поменял на способ с деструктуризацией

2020-10-01 06:59 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +    this.set('results', this.get('treeContent'));
Хм, мне кажется что на первоначальном клике пользователю должна показываться полная менюшка, чтобы он был убежден в том, что поиск работает и можно вводить строку. Думаешь, что это так себе идея?

2020-10-01 07:01 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +      }
Ого, не знал даже о такой функции

2020-10-01 14:32 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +  },
Поменял последние три условия на `isEmpty(element.children)`

2020-10-01 14:36 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +      if ((query === null || query === 'undefined' || query === '')) {
Да, никак не поспоришь.

2020-10-01 15:34 UTC, dpavloff commented on app/templates/components/flexberry-sitemap-searchbar.hbs
> +  <div id="results-list">
Вынес placeholder, убрал айдишники.

2020-10-02 07:21 UTC, dpavloff commented on app/templates/components/flexberry-sitemap-searchbar.hbs
> +    {{/searchbar-node}}
Сделано

2020-10-02 07:39 UTC, dpavloff commented on app/templates/sitemap.hbs
> +treeContent=model.nodes}}
Перенёс в application.hbs.

2020-10-21 11:08 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +    $sitemapSearch.addEventListener('input', (e) => {
Оставил только событие `$(document).on('click)`, т.к. не могу найти другого способа проверять клик не по компоненту.

2020-10-21 11:10 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +    this.set('results', this.get('treeContent'));
Убрал.

2020-10-21 11:12 UTC, dpavloff commented on addon/components/flexberry-sitemap-searchbar.js
> +      } else if (this._elementHasChildren(element)) {
Записываю копию `element` с помощью lodash.

2022-12-29 03:35 UTC, turbcool commented
Документация https://github.com/Flexberry/flexberry.github.io/pull/121

2023-02-13 08:26 UTC, pepelyaeva commented
Нужно исправить под 3 версию

2023-08-08 16:55 UTC, pepelyaeva requested changes

2023-08-08 16:55 UTC, pepelyaeva commented on app/templates/components/flexberry-sitemap-searchbar.hbs
> +<div class="sitemap-searchbar ui search">
Это же в classNames вынесено уже. Обертку можно удалить

2023-08-08 16:55 UTC, pepelyaeva commented on app/templates/components/flexberry-sitemap-searchbar.hbs
> +  placeholder=placeholder
форматирование

2023-08-08 16:55 UTC, pepelyaeva commented on app/templates/components/flexberry-sitemap-searchbar.hbs
> +      }}
форматирование

2023-08-08 16:55 UTC, pepelyaeva commented on app/templates/components/flexberry-sitemap-searchbar.hbs
> +            </span>
Лучше это в одну строку записать

2023-08-08 16:55 UTC, pepelyaeva commented on tests/dummy/app/templates/application.hbs
> +    sitemap=sitemap.nodes}}
Лучше в одну строку

2023-08-08 16:55 UTC, pepelyaeva commented on addon/components/flexberry-sitemap-searchbar.js
Надо добавить скрытие при потере фокуса, а то я перешла на страницу из поиска а поле так и осталось открытым
![image](https://github.com/Flexberry/ember-flexberry/assets/15091209/5e675d02-9d52-43cd-adf7-d3901b7c10fc)

2023-08-08 16:55 UTC, pepelyaeva commented on addon/components/flexberry-sitemap-searchbar.js
Еще такой сценарий:
Свернуть меню, нажать на иконку поиска, кликнуть на любом месте формы - скрывается список с результатами.
Кликнуть еще раз по иконке поиска - скрывается поле ввода но отображается список с результатами

2023-08-08 16:55 UTC, pepelyaeva commented on .eslint-todo-errors.json
> +  ],
А вот эти все замечания надо бы поправить

2023-08-08 16:55 UTC, pepelyaeva commented on .template-lintrc.js
> +    },
и это поправить, а не писать в исключения

2023-08-11 07:39 UTC, pepelyaeva approved these changes

2023-08-11 08:32 UTC, DubrovinPavel approved these changes

2023-08-11 10:04 UTC, merged