Added hasShadow and hasBorder properties for flexberry-toggler
Flexberry/ember-flexberry pull request #1211
Opened 2020-09-28 11:52 UTC by dpavloff

Also added tests for relevant properties

2020-10-01 07:02 UTC, KollegOFF requested changes
Нужно перенести стили в тему `blue-sky`, для темы `orange` можно не делать.
Тема `default` это скопированные стили из какой то версии `Semantic UI`, её планируется удалить.

2020-10-05 11:52 UTC, dpavloff commented on addon/styles/themes/default/modules/accordion.overrides
> +.has-shadow {
Как насчёт ".toggler-has-border"?

2020-10-22 10:19 UTC, KollegOFF commented on addon/styles/themes/default/modules/accordion.overrides
> +.has-shadow {
У компонента уже есть класс `flexberry-toggler`, можно сделать `.flexberry-toggler.has-border`.

2020-10-22 10:22 UTC, pepelyaeva commented on tests/dummy/app/templates/components-examples/flexberry-toggler/settings-example.hbs
> +        hasShadow=hasShadow
А зачем это в отдельных свойствах, может просто классы добавлять?

2020-10-26 08:28 UTC, pepelyaeva commented
https://github.com/Flexberry/ember-flexberry-themes/pull/91

2020-10-26 13:59 UTC, dpavloff commented on tests/dummy/app/templates/components-examples/flexberry-toggler/settings-example.hbs
> +        hasShadow=hasShadow
Если мне не изменяет память, из задачи следовало, что необходимо сделать свойства. @lulzforme, поправь меня, если что.

2020-11-13 08:23 UTC, KollegOFF approved these changes

2020-11-15 06:11 UTC, merged