Feature default user settings in lookup
Flexberry/ember-flexberry pull request #1229
Opened 2020-11-25 08:20 UTC by emchigesheva

#1226

2020-11-26 06:50 UTC, mao29 requested changes

2020-11-26 06:50 UTC, mao29 commented on package.json
> +  "version": "2.0.0",
Почему версия откатилась на какую-то очень старую?

2020-11-26 12:56 UTC, emchigesheva commented on package.json
> +  "version": "2.0.0",
случайность, поправила

2020-11-26 15:18 UTC, KollegOFF commented on tests/acceptance/components/flexberry-lookup/flexberry-lookup-default-user-setting-test.js
> +  visit('components-acceptance-tests/flexberry-lookup/settings-example-projection');
Нужно сделать отдельную форму в `dummy`-приложении, и на ней тестировать.
Только её не надо так далеко прятать, можно рядом со всеми положить.

2020-11-27 05:24 UTC, emchigesheva commented on app/templates/lookup-dialog-content.hbs
> +    modelName=modelType
ага, согласна, просто не увидела сразу

2020-11-27 05:34 UTC, emchigesheva commented on addon/components/object-list-view.js
> +    }
в моем варианте да, но наверное надо предусмотреть оба варианта установки

2020-12-01 08:13 UTC, mao29 commented on tests/dummy/app/instance-initializers/default-user-settings.js
> +  applicationInstance.register('user-setting:ember-flexberry-dummy-suggestion-type', SuggestionTypeDefaultUserSettings.DEFAULT, { instantiate: false });
А нет способа какой-то инициализатор сделать, который по конвенции будет все default-user-settings/* собирать и регистрировать? Неудобно же вручную импорты дописывать и регистрировать.

2020-12-06 10:49 UTC, KollegOFF commented on tests/acceptance/components/flexberry-lookup/flexberry-lookup-default-user-setting-test.js
> +/* eslint-disable no-undef */
```suggestion
/* global visit, andThen */
```
Так не получается?

2020-12-06 10:49 UTC, KollegOFF commented on tests/acceptance/components/flexberry-lookup/flexberry-lookup-prefer-developer-to-default-user-setting-test.js
> +});
Это ещё актуально?
Тут настраивается не та форма, что используется в тесте.

2020-12-06 10:49 UTC, KollegOFF commented on tests/acceptance/components/flexberry-lookup/flexberry-lookup-prefer-stored-to-default-user-setting-test.js
> +    // eslint-disable-next-line ember/no-jquery
Это ворнинги, их не нужно отключать.
https://github.com/Flexberry/ember-flexberry/blob/d68ae2179a92f1d0f9c80736bfa5f1ad52919015/.eslintrc.js#L32

2020-12-06 10:49 UTC, KollegOFF commented on tests/dummy/app/default-user-settings/suggestion-type.js
> +  }`;
Не понимаю в чём плюс возможности описания этих настроек строкой.
Мне кажется, лучше только объектом их описывать, как `developerUserSettings`.

2020-12-06 10:49 UTC, KollegOFF commented on tests/dummy/app/instance-initializers/default-user-settings.js
> +  applicationInstance.register('user-setting:ember-flexberry-dummy-suggestion-type', SuggestionTypeDefaultUserSettings.DEFAULT, { instantiate: false });
Все равно где то должен быть явный импорт файла с настройками, иначе, думаю он не попадет в приложение при продакшен сборке.
Меня как то напрягают инициалайзеры, я бы лучше добавил `index.js` с импортом всех файлов, а его импортировал бы в `app.js`. Это тоже можно добавить в блюпринт.

2020-12-07 04:34 UTC, mao29 commented on tests/dummy/app/instance-initializers/default-user-settings.js
> +  applicationInstance.register('user-setting:ember-flexberry-dummy-suggestion-type', SuggestionTypeDefaultUserSettings.DEFAULT, { instantiate: false });
Интересно просто как родные работают регистраторы всех файлов по конвенции. Причем и сторонние аддоны есть вроде бы, которые так делают.

2020-12-20 16:33 UTC, merged