Styles highload menu component
Flexberry/ember-flexberry pull request #1351
Opened 2022-08-15 09:56 UTC by mari4orl

2022-09-06 12:34 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +      }
set(razdel, 'active', activeRazdel)

2022-09-06 13:09 UTC, pepelyaeva requested changes

2022-09-06 13:09 UTC, pepelyaeva commented on app/templates/components/highload-edit-form-menu.hbs
> +<div class="ui two column grid highloaded-menu-container">
Лучше указать через classNames: ['highloaded-menu-container'] в контроллере

2022-09-06 13:09 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +      }
set(razdel, 'active', activeRazdel);

2022-09-06 13:09 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
>    },
В #1352  нашла метод setMenuForTemplate, дублирует этот код, нужно обновиться

2022-09-07 07:17 UTC, mari4orl commented on app/templates/components/highload-edit-form-menu.hbs
> +<div class="ui two column grid highloaded-menu-container">
Исправлено

2022-09-07 07:18 UTC, mari4orl commented on addon/components/highload-edit-form-menu.js
> +      }
Исправлено

2022-09-07 07:37 UTC, mari4orl commented on addon/components/highload-edit-form-menu.js
>    },
Исправлено

2022-09-07 10:22 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +
Лишняя строка

2022-09-07 10:22 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +    menu[0].active = true;
Лишнее

2022-09-07 10:26 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +      set(razdel, 'active', activeRazdel);
Надо откатить, это Света исправит в своей ветке

2022-09-07 10:26 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +
Лишняя строка

2022-09-07 10:29 UTC, pepelyaeva commented on app/templates/components/highload-edit-form-menu.hbs
> +      class="tabsNavigation ui primary button"
здесь можно оставить просто primary, классы ui button уже заданы в компоненте flexberry-button

2022-09-07 10:45 UTC, mari4orl commented on app/templates/components/highload-edit-form-menu.hbs
> +      class="tabsNavigation ui primary button"
Исправлено

2022-09-07 10:45 UTC, mari4orl commented on addon/components/highload-edit-form-menu.js
> +
Исправлено

2022-09-07 10:45 UTC, mari4orl commented on addon/components/highload-edit-form-menu.js
> +      set(razdel, 'active', activeRazdel);
Исправлено

2022-09-07 10:45 UTC, mari4orl commented on addon/components/highload-edit-form-menu.js
> +    menu[0].active = true;
Исправлено

2022-09-07 10:45 UTC, mari4orl commented on addon/components/highload-edit-form-menu.js
> +
Исправлено

2022-09-07 11:06 UTC, pepelyaeva commented on app/templates/components/highload-edit-form-menu.hbs
> +            <div class="one wide column">
Блоки внутри меню не надо задавать через column, они на разных мониторах будут разной ширины, должны быть одинаковой

2022-09-07 11:13 UTC, pepelyaeva commented on app/templates/components/highload-edit-form-menu.hbs
> +      iconClass="icon icon-guideline-arrow-short-down"
icon-guideline-navigate-arrow-down, надо шрифт обновить и поюзать эту иконку

2022-09-07 11:15 UTC, pepelyaeva commented on app/templates/components/highload-edit-form-menu.hbs
> +      iconClass="icon icon-guideline-arrow-short-up"
вверх такую не нашла, надо будет добавить ее в шрифт

2022-09-07 11:16 UTC, pepelyaeva commented on app/templates/components/highload-edit-form-menu.hbs
> +      class="ui secondary basic button tabsNavigation"
basic это кнопка с бордером, нужна empty

2022-09-08 06:29 UTC, mari4orl commented on app/templates/components/highload-edit-form-menu.hbs
> +            <div class="one wide column">
Исправлено

2022-09-08 06:29 UTC, mari4orl commented on app/templates/components/highload-edit-form-menu.hbs
> +      class="ui secondary basic button tabsNavigation"
Исправлено

2022-09-08 07:09 UTC, mari4orl commented on app/templates/components/highload-edit-form-menu.hbs
> +      iconClass="icon icon-guideline-arrow-short-down"
Исправлено

2022-09-08 09:48 UTC, mari4orl commented on app/templates/components/highload-edit-form-menu.hbs
> +      iconClass="icon icon-guideline-arrow-short-up"
Исправлено

2022-09-16 09:48 UTC, pepelyaeva approved these changes

2022-09-16 09:48 UTC, merged