Highload menu component
Flexberry/ember-flexberry pull request #1352
Opened 2022-08-18 06:18 UTC by TeterinaSvetlana

2022-09-06 13:10 UTC, pepelyaeva requested changes

2022-09-06 13:10 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +    }
this.razdelNumeration = this.menu.length > 1

2022-09-06 13:10 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +    document.getElementsByClassName('full height')[0].addEventListener('wheel', function() {
Думаю, нужно дать возможность задавать селектор, он не везде full height

2022-09-06 13:10 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +        set(razdel, 'active', false);
set(razdel, 'active', activeRazdel);

2022-09-06 13:10 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +          activeRazdel = true;
breack?

2022-09-15 15:48 UTC, TeterinaSvetlana commented on addon/components/highload-edit-form-menu.js
> +          activeRazdel = true;
добавила return

2022-09-15 15:56 UTC, TeterinaSvetlana commented on addon/components/highload-edit-form-menu.js
> +    document.getElementsByClassName('full height')[0].addEventListener('wheel', function() {
добавила, full height поставила в качестве дефолта

2022-09-16 10:20 UTC, pepelyaeva commented on addon/components/highload-edit-form-menu.js
> +          }
Зачем тут if, может сразу проставить результат сравнения в child?

2022-09-16 10:21 UTC, pepelyaeva commented on app/templates/components/highload-edit-form-menu.hbs
> +      caption="Назад"
Через локали надо задать

2022-09-16 13:35 UTC, TeterinaSvetlana commented on addon/components/highload-edit-form-menu.js
> +          }
поменяла

2022-09-16 13:46 UTC, merged