Add page with icons
Flexberry/ember-flexberry pull request #1387
Opened 2022-12-07 14:59 UTC by mari4orl

2022-12-08 08:07 UTC, pepelyaeva requested changes

2022-12-08 08:07 UTC, pepelyaeva commented on ember-cli-build.js
> +    const ghostThemeAssetsDir = 'node_modules/ember-flexberry-themes/src/themes/ghost/assets';
ember-flexberry-themes же в бовере тут, в node_modules нет этого пакета.
И тут 2 пробела дб, а не 4

2022-12-08 08:07 UTC, pepelyaeva commented on package.json
> +    "lodash": "^4.4.0",
Это нужно все отменить

2022-12-08 08:07 UTC, pepelyaeva commented on tests/dummy/app/templates/integration-examples/ember-flexberry-icons.hbs
> +<h3>Иконки</h3>
Заголовок из локалей надо взять

2022-12-08 08:07 UTC, pepelyaeva commented on tests/dummy/app/templates/integration-examples/ember-flexberry-icons.hbs
> +      <div class="block-icon"><i class="icon-guideline-clear-layers"><p>icon-guideline-clear-layers</p></i></div>
Не надо `<p> в <i>` складывать.
Что если сложить все названия иконок в массив в контроллере  и тут #each заюзать?

2022-12-08 08:07 UTC, pepelyaeva commented on yarn.lock
> +
Откатить

2022-12-08 08:07 UTC, pepelyaeva commented on tests/dummy/app/styles/icon-page.less
> +.icon-container {
Почему сетку семантика не использовать? в одну колонку, например

2022-12-08 08:07 UTC, pepelyaeva commented on tests/dummy/app/styles/icon-page.less
> +    font-family: 'Helvetica Neue', Arial, Helvetica, sans-serif;
Шрифт должен быть стандартный

2022-12-08 08:07 UTC, pepelyaeva commented on tests/dummy/app/styles/icon-page.less
> +    background: #ECF2FB none;
Все цвета из надо использовать из переменных

2022-12-08 08:07 UTC, pepelyaeva commented on tests/dummy/app/styles/icon-page.less
> +  & p {
Зачем тут & если после него все равно пробел

2022-12-08 08:07 UTC, pepelyaeva commented on tests/dummy/app/router.js
> +  this.route('integration-examples/ember-flexberry-icons');
Надо переместить выше в раздел Integration examples routes

2022-12-09 08:56 UTC, mari4orl commented on tests/dummy/app/styles/icon-page.less
> +  & p {
Исправлено

2022-12-09 08:58 UTC, mari4orl commented on tests/dummy/app/router.js
> +  this.route('integration-examples/ember-flexberry-icons');
Испрвалено

2022-12-09 08:58 UTC, mari4orl commented on tests/dummy/app/styles/icon-page.less
> +    font-family: 'Helvetica Neue', Arial, Helvetica, sans-serif;
Испрвалено

2022-12-09 08:58 UTC, mari4orl commented on tests/dummy/app/styles/icon-page.less
> +.icon-container {
Испрвалено

2022-12-09 08:58 UTC, mari4orl commented on yarn.lock
> +
Испрвалено

2022-12-09 08:58 UTC, mari4orl commented on tests/dummy/app/templates/integration-examples/ember-flexberry-icons.hbs
> +      <div class="block-icon"><i class="icon-guideline-clear-layers"><p>icon-guideline-clear-layers</p></i></div>
Испрвалено

2022-12-09 08:58 UTC, mari4orl commented on tests/dummy/app/templates/integration-examples/ember-flexberry-icons.hbs
> +<h3>Иконки</h3>
Испрвалено

2022-12-09 08:58 UTC, mari4orl commented on package.json
> +    "lodash": "^4.4.0",
Испрвалено

2022-12-09 10:12 UTC, mari4orl commented on ember-cli-build.js
> +    const ghostThemeAssetsDir = 'node_modules/ember-flexberry-themes/src/themes/ghost/assets';
Исправлено

2022-12-09 10:12 UTC, mari4orl commented on tests/dummy/app/styles/icon-page.less
> +    background: #ECF2FB none;
Исправлено

2022-12-09 10:27 UTC, pepelyaeva requested changes

2022-12-09 10:27 UTC, pepelyaeva commented on ember-cli-build.js
> +  const ghostThemeAssetsDir = 'bower/ember-flexberry-themes/src/themes/ghost/assets';
Бовер пакеты выкачиваются в папку bower_components

2022-12-09 10:27 UTC, pepelyaeva commented on tests/dummy/app/styles/app.less
> +@import 'icon-page';
Этот иморт надо удалить

2022-12-09 10:27 UTC, pepelyaeva commented on tests/dummy/app/styles/icon-page.less
> +// .block-icon {
Этот файл надо удалить

2022-12-09 12:26 UTC, mari4orl commented on tests/dummy/app/styles/icon-page.less
> +// .block-icon {
Исправлено

2022-12-09 12:26 UTC, mari4orl commented on tests/dummy/app/styles/app.less
> +@import 'icon-page';
Исправлено

2022-12-09 12:27 UTC, mari4orl commented on ember-cli-build.js
> +  const ghostThemeAssetsDir = 'bower/ember-flexberry-themes/src/themes/ghost/assets';
Исправлено

2022-12-12 09:42 UTC, pepelyaeva commented on ember-cli-build.js
> +  app.import(`${ghostThemeAssetsDir}/fonts/guideline-icons/guideline-icons.svg`, { destDir: 'assets/fonts/guideline-icons' });
Оставь тут destDir: 'assets/fonts'. Так как сейчас не работают шрифты

2022-12-12 10:00 UTC, pepelyaeva commented on tests/dummy/app/styles/site/ghost/pages/edit-form.overrides
> +    font-size: 32px;
Размер шрифта надо задавать для i а не для before

2022-12-13 11:52 UTC, mari4orl commented on tests/dummy/app/styles/site/ghost/pages/edit-form.overrides
> +    font-size: 32px;
Исправлено

2022-12-13 11:52 UTC, mari4orl commented on ember-cli-build.js
> +  app.import(`${ghostThemeAssetsDir}/fonts/guideline-icons/guideline-icons.svg`, { destDir: 'assets/fonts/guideline-icons' });
Исправлено

2022-12-13 12:03 UTC, pepelyaeva approved these changes

2022-12-13 12:05 UTC, merged