Added functionality to embed custom components in the olv-toolbar
Flexberry/ember-flexberry pull request #1456
Opened 2023-07-06 08:02 UTC by neroslovegor

2023-07-07 10:56 UTC, s-andrey commented on addon/components/olv-toolbar.js
> +    @property customToolbarComponents
имя не то

2023-07-10 04:56 UTC, DubrovinPavel approved these changes

2023-07-12 10:16 UTC, VChurekov approved these changes

2023-07-13 09:08 UTC, AntonIV8 requested changes

2023-07-13 09:08 UTC, AntonIV8 commented on tests/dummy/app/locales/en/translations.js
> +          'caption': 'Flexberry-objectlistview. Example of embedding custom components in olv-toolbar',
не надо запятую в конце

2023-07-13 09:08 UTC, AntonIV8 commented on tests/dummy/app/locales/ru/translations.js
> +          'caption': 'Flexberry-objectlistview. Пример встраивания пользовательских компонентов в olv-toolbar',
не надо запятую в конце

2023-07-14 05:39 UTC, AntonIV8 approved these changes

2023-07-14 05:49 UTC, merged