Add multiselect
Flexberry/ember-flexberry pull request #1457
Opened 2023-07-06 20:39 UTC by TeterinaSvetlana

2023-07-07 11:36 UTC, s-andrey commented on addon/components/flexberry-objectlistview.js
> +   * Флаг для выделения выбранных записей в модальном окне
у нас в аддоне все комменты на англ

2023-07-07 11:36 UTC, s-andrey commented on addon/controllers/lookup-dialog.js
> +import Ember from 'ember';
убрать

2023-07-07 11:36 UTC, s-andrey commented on addon/controllers/lookup-dialog.js
> +} = Ember;
импортировать из пакетов

2023-07-07 11:36 UTC, s-andrey commented on addon/locales/en/translations.js
> +      pullUpLookupValues: 'Use all selected records',
убрать запятую в конце

2023-07-07 11:36 UTC, s-andrey commented on addon/locales/ru/translations.js
> +      pullUpLookupValues: 'Использовать все выбранные записи',
убрать запятую в конце

2023-07-07 11:36 UTC, s-andrey commented on addon/mixins/flexberry-lookup-controller.js
> +} = Ember;
зачем? убрать

2023-07-07 11:36 UTC, s-andrey commented on addon/mixins/flexberry-lookup-controller.js
> +      let disableHierarchy = Ember.get(options, 'lookupWindowCustomPropertiesData.disableHierarchicalMode');
Ember. ? это вообще работает? (импорта эмбера ведь нет) надо поправить тут и ниже

2023-07-07 11:36 UTC, s-andrey commented on addon/services/objectlistview-events.js
> +import Ember from 'ember';
убрать

2023-07-07 11:36 UTC, s-andrey commented on addon/services/objectlistview-events.js
> +} = Ember;
исправить импорт

2023-07-07 11:36 UTC, s-andrey commented on addon/services/objectlistview-events.js
> +  getMultiSelectedRecords(componentName) {
комменты надо добавить тут и ниже

2023-07-07 11:36 UTC, s-andrey commented on app/templates/ge-multi-lookup-dialog-content.hbs
> +    componentMode='lookupform'
ковычки двойные

2023-07-07 11:36 UTC, s-andrey commented on app/templates/ge-multi-lookup-dialog-content.hbs
> +    filterByAnyMatch=(action 'filterByAnyMatch')
ковычки

2023-07-10 08:53 UTC, DubrovinPavel commented on addon/components/object-list-view.js
> +  skipSelectedRecords: true,
нужен комментарий

2023-07-10 08:54 UTC, DubrovinPavel commented on addon/controllers/lookup-dialog.js
> +import { get } from '@ember/object';
можно объединить импорт из @ember/object

2023-07-10 08:54 UTC, DubrovinPavel commented on addon/controllers/lookup-dialog.js
> +  isPullUpActive: false,
Комментарий

2023-07-13 06:35 UTC, AntonIV8 requested changes

2023-07-13 06:35 UTC, AntonIV8 commented on addon/components/object-list-view.js
> +        this.get('skipSelectedRecords') === false) {
наверное это условие надо первым проверять

Также возможно
selectedRecordsToRestore &&
selectedRecordsToRestore.size && 
selectedRecordsToRestore.size > 0

можно заменить на !isEmpty(selectedRecordsToRestore). Но надо проверить

https://api.emberjs.com/ember/3.2/functions/@ember%2Futils/isEmpty

2023-07-13 06:35 UTC, AntonIV8 commented on addon/controllers/lookup-dialog.js
> +      let currentLookupRow = this.get('currentLookupRow');
тоже const

2023-07-13 06:35 UTC, AntonIV8 commented on addon/controllers/lookup-dialog.js
> +      const detail = contextModel.get(relName);
а это вроде не const

2023-07-13 06:35 UTC, AntonIV8 commented on addon/locales/en/translations.js
> +      pullUpLookupValues: 'Use all selected records'
может по подобию назвать ?

2023-07-13 06:35 UTC, AntonIV8 commented on addon/mixins/flexberry-lookup-controller.js
> +      let disableHierarchy = get(options, 'lookupWindowCustomPropertiesData.disableHierarchicalMode');
const и ниже все тоже

2023-07-13 06:35 UTC, AntonIV8 commented on addon/mixins/flexberry-lookup-controller.js
> +      const relName = get(this.get('model').constructor, 'relationships').get(model.constructor.modelName)[0].name;
лучше не сокращать слова в названиях. Т.к relationName уже есть выше, то relationName и relName разные по смыслу. Это надо в названии переменной отразить

2023-07-13 06:35 UTC, AntonIV8 commented on addon/services/objectlistview-events.js
> +      this.get('_multiRows')[componentName] = Ember.Map.create();
Там EmberMap импортируется, его надо наверное использовать (Ниже тоже везде). А импорт Ember тогда и не нужен скорее всего

2023-07-13 06:35 UTC, AntonIV8 commented on addon/services/objectlistview-events.js
> +  _multiRows: null,
Комментарий

2023-07-13 06:35 UTC, AntonIV8 commented on tests/dummy/app/controllers/components-examples/flexberry-groupedit/groupedit-with-multiselect-edit.js
> +          break;
Линтер не ругается, что default нет ?

2023-07-13 06:35 UTC, AntonIV8 commented on tests/dummy/app/controllers/components-examples/flexberry-groupedit/groupedit-with-multiselect-edit.js
> +    let i18n = this.get('i18n');
const

2023-07-13 06:35 UTC, AntonIV8 commented on tests/dummy/app/controllers/components-examples/flexberry-groupedit/groupedit-with-multiselect-edit.js
> +          let lookupSettings = this.get('lookupMultiGESettings');
const

2023-07-13 06:35 UTC, AntonIV8 commented on tests/dummy/app/routes/components-examples/flexberry-groupedit/groupedit-with-multiselect-edit.js
> +
не надо пустую строку

2023-07-14 05:37 UTC, TeterinaSvetlana commented on tests/dummy/app/controllers/components-examples/flexberry-groupedit/groupedit-with-multiselect-edit.js
> +          break;
вроде нет

2023-07-14 07:33 UTC, DubrovinPavel approved these changes

2023-07-14 08:37 UTC, AntonIV8 requested changes

2023-07-14 08:37 UTC, AntonIV8 commented on addon/components/object-list-view.js
> +      if (this.get('skipSelectedRecords') === false && !isEmpty(selectedRecordsToRestore)) {
пробел

2023-07-14 08:59 UTC, AntonIV8 approved these changes

2023-07-14 09:04 UTC, merged