Added dropdown in the filter for directories
Flexberry/ember-flexberry pull request #1464
Opened 2023-07-12 07:29 UTC by neroslovegor

2023-07-12 12:42 UTC, AntonIV8 requested changes

2023-07-12 12:42 UTC, AntonIV8 commented on addon/components/object-list-view.js
> +    if (isEmpty(this.ddlFilterSettings)) {
а тут не this.get('ddlFilterSettings')

2023-07-12 12:42 UTC, AntonIV8 commented on addon/components/object-list-view.js
> +    return RSVP.all(promises);
А если вдруг запросы не смогут выполниться, то получается в ddlFilterSettings items может не быть. Дальше там нигде не упадет из-за этого ?

2023-07-12 12:42 UTC, AntonIV8 commented on addon/components/object-list-view.js
> +      return {
эмм, а что будет возвращаться, если !element

2023-07-13 04:37 UTC, DubrovinPavel commented on addon/components/object-list-view.js
> +    const promises =  A([]);
Можно просто A();

2023-07-13 05:09 UTC, neroslovegor commented on addon/components/object-list-view.js
> +    return RSVP.all(promises);
Не упадет, выпадающий список не будет открываться.

2023-07-13 06:39 UTC, AntonIV8 approved these changes

2023-07-13 11:12 UTC, DubrovinPavel approved these changes

2023-07-14 05:15 UTC, VChurekov approved these changes

2023-07-14 10:39 UTC, merged