Codemods for updateLookupValue
Flexberry/ember-flexberry pull request #1466
Opened 2023-07-14 04:49 UTC by torres6093

2023-07-14 06:22 UTC, VChurekov commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/__testfixtures__/basic.input.js
> +    var cellComponent = this._super(...arguments);
let или const

2023-07-14 06:22 UTC, VChurekov commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/__testfixtures__/basic.output.js
> +    var cellComponent = this._super(...arguments);
let или const

2023-07-14 06:22 UTC, VChurekov commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/README.md
> +npx ember-flexberry-codemod lookup-getCellComponent path/of/files/ or/some**/*glob.js
Может тут тоже подробнее описать как в readme повыше?

2023-07-14 06:22 UTC, VChurekov commented on codemodes/ember-flexberry-codemod/transforms/lookup-hbs/README.md
> +npx ember-flexberry-codemod lookup-hbs path/of/files/ or/some**/*glob.hbs
Может тут тоже подробнее описать как в readme кодмодов?

2023-07-16 07:50 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/__testfixtures__/basic.input.js
> +    var cellComponent = this._super(...arguments);
Сделал let

2023-07-16 07:50 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/__testfixtures__/basic.output.js
> +    var cellComponent = this._super(...arguments);
Сделал let

2023-07-16 07:51 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/README.md
> +npx ember-flexberry-codemod lookup-getCellComponent path/of/files/ or/some**/*glob.js
Решили удалить, оставив лишь общий readme

2023-07-16 07:51 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-hbs/README.md
> +npx ember-flexberry-codemod lookup-hbs path/of/files/ or/some**/*glob.hbs
Решили удалить, оставив лишь общий readme

2023-07-19 05:59 UTC, AntonIV8 requested changes

2023-07-19 05:59 UTC, AntonIV8 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/index.js
> +  // Применяем необходимые изменения к каждому файлу
точка в конце

2023-07-19 05:59 UTC, AntonIV8 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/index.js
> +    // Проверяем, содержит ли уже тело блока if переменную updateLookupValue
точка в конце

2023-07-19 05:59 UTC, AntonIV8 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/index.js
> +    // Если переменная updateLookupValue не существует, добавляем ее в начало
точка в конце

2023-07-19 05:59 UTC, AntonIV8 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/index.js
> +    let updateLookupValueProperties = objectProperties.paths().find((prop) => prop.value.key.name === 'updateLookupValue');
const

2023-07-19 05:59 UTC, AntonIV8 commented on codemodes/ember-flexberry-codemod/transforms/lookup-hbs/index.js
> +// то для такого элемента добавляется свойство updateLookupValue
точка в конце

2023-07-19 05:59 UTC, AntonIV8 commented on codemodes/ember-flexberry-codemod/transforms/lookup-hbs/index.js
> +        }
пустая строка после if

2023-07-19 10:07 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/index.js
> +  // Применяем необходимые изменения к каждому файлу
done

2023-07-19 10:07 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/index.js
> +    // Проверяем, содержит ли уже тело блока if переменную updateLookupValue
done

2023-07-19 10:07 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/index.js
> +    // Если переменная updateLookupValue не существует, добавляем ее в начало
done

2023-07-19 10:07 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-getCellComponent/index.js
> +    let updateLookupValueProperties = objectProperties.paths().find((prop) => prop.value.key.name === 'updateLookupValue');
done

2023-07-19 10:07 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-hbs/index.js
> +// то для такого элемента добавляется свойство updateLookupValue
done

2023-07-19 10:07 UTC, torres6093 commented on codemodes/ember-flexberry-codemod/transforms/lookup-hbs/index.js
> +        }
done

2023-07-19 11:04 UTC, AntonIV8 approved these changes

2023-07-21 06:45 UTC, merged