Column width customization test
Flexberry/ember-flexberry pull request #673
Opened 2018-08-24 12:20 UTC by TeterinaSvetlana

2018-08-31 10:44 UTC, KollegOFF requested changes

2018-08-31 10:44 UTC, KollegOFF commented on tests/acceptance/components/flexberry-objectlistview/folv-column-width-customization-test.js
> +              Ember.$('input.columnWidth')[0].value = 50;
The same thing is done 14 times?

2018-08-31 10:44 UTC, KollegOFF commented on tests/acceptance/components/flexberry-objectlistview/folv-column-width-customization-test.js
> +          assert.equal($($component).hasClass('checked'), false, 'Width config is OFF');
You can simply use the function [`assert.notOk`](https://api.qunitjs.com/assert/notOk) instead of comparing with `false`.

2018-08-31 10:44 UTC, KollegOFF commented on tests/acceptance/components/flexberry-objectlistview/folv-column-width-customization-test.js
> +            assert.equal($($component).hasClass('checked'), true, 'Width config is ON');
In this case, the [`assert.ok`](https://api.qunitjs.com/assert/ok) function works for you, and if you need a strict comparison then the [`assert.strictEqual`](https://api.qunitjs.com/assert/strictEqual) function.

2018-08-31 10:44 UTC, KollegOFF commented on tests/acceptance/components/flexberry-objectlistview/folv-column-width-customization-test.js
> +                      setTimeout(function() {}, 17000);
What is it?

2018-08-31 10:44 UTC, KollegOFF commented on tests/acceptance/components/flexberry-objectlistview/folv-column-width-customization-test.js
> +                  }, 17000);
And why not 17001?

2018-08-31 10:44 UTC, KollegOFF commented on tests/acceptance/components/flexberry-objectlistview/folv-column-width-customization-test.js
> +                  done3();
I do not understand why there are so many calls to the functions `assert.async` and `done`?

2019-01-14 07:47 UTC, KollegOFF requested changes

2019-01-14 07:47 UTC, KollegOFF commented on tests/acceptance/components/flexberry-objectlistview/folv-column-width-customization-test.js
> +          assert.notOk($($component).hasClass('disabled'), true, 'Width values is ON');
The functions [`assert.ok`](https://api.qunitjs.com/assert/ok) and [`assert.notOk`](https://api.qunitjs.com/assert/notOk) have only two parameters.

2019-01-14 07:47 UTC, KollegOFF commented on tests/acceptance/components/flexberry-objectlistview/folv-column-width-customization-test.js
> +                  assert.equal($component[5].className === 'toggle ember-view flexberry-checkbox ui checkbox', true, 'Width config is OFF');
With such a check, if the order of classes is changed, the check will fail. It is better to check the availability of the required class.

2019-01-14 07:47 UTC, KollegOFF commented on tests/acceptance/components/flexberry-objectlistview/folv-column-width-customization-test.js
> +                  setTimeout(function() {
Is there really a need for all these `setTimeout` calls, without them the test is not working?

2023-02-20 12:48 UTC, pepelyaeva commented
В связи с текущей реализацией подсчета ширины колонки, данный пр является неактуальным.

2023-02-20 12:48 UTC, closed without merging