Add modal fo edit
Flexberry/ember-flexberry pull request #802
Opened 2019-05-31 06:08 UTC by AntonIV8

2023-02-13 12:42 UTC, pepelyaeva commented
Нужно исправить под 3 версию

2023-04-04 07:41 UTC, pepelyaeva requested changes

2023-04-04 07:41 UTC, pepelyaeva commented on addon/components/flexberry-simpleolv.js
Надо удалить, этого компонента в 3 версии нет

2023-04-04 07:41 UTC, pepelyaeva commented on addon/components/modal-dialog.js
> +    showHeader: true,
Много пробелов

2023-04-04 07:41 UTC, pepelyaeva commented on addon/components/olv-toolbar.js
> +    editInModal: false,
много пробелов, должно быть 2

2023-04-04 07:41 UTC, pepelyaeva commented on addon/components/olv-toolbar.js
> +        Ember.run.later((function() {
import { later } from '@ember/runloop';

2023-04-04 07:41 UTC, pepelyaeva commented on addon/controllers/edit-form.js
> +    if (isModal && !Ember.isNone(modalController)) {
import { isNone } from '@ember/utils';

2023-04-04 07:41 UTC, pepelyaeva commented on addon/controllers/edit-form.js
> +    },
Пробелы

2023-04-04 07:41 UTC, pepelyaeva commented on addon/controllers/editrecord-dialog.js
> +  objectlistviewEvents: Ember.inject.service(),
import { inject as service} from '@ember/service'; и ниже

2023-04-04 07:41 UTC, pepelyaeva commented on addon/controllers/editrecord-dialog.js
> +export default Ember.Controller.extend({
import Controller from '@ember/controller';

2023-04-04 07:41 UTC, pepelyaeva commented on addon/mixins/edit-in-modal-open.js
> +  objectlistviewEvents: Ember.inject.service(),
import { inject as service} from '@ember/service';

2023-04-04 07:41 UTC, pepelyaeva commented on addon/mixins/edit-in-modal-open.js
> +    let modalController = Ember.getOwner(this).lookup('controller:' + modalControllerName);
import { getOwner } from '@ember/application';

2023-04-04 07:41 UTC, pepelyaeva commented on addon/mixins/edit-in-modal-open.js
> +    let modalContentController = Ember.getOwner(this).lookup('controller:' + modalContentControllerName);
import { getOwner } from '@ember/application';

2023-04-04 07:41 UTC, pepelyaeva commented on addon/mixins/edit-in-modal-open.js
> +    let modelProjName = Ember.getOwner(this).lookup('route:' + editFormRoute).get('modelProjection');
import { getOwner } from '@ember/application';

2023-04-04 07:41 UTC, pepelyaeva commented on addon/mixins/flexberry-objectlistview-route.js
> +          parentRouteRecordId: thisRecordId
Пробелы

2023-04-04 07:41 UTC, pepelyaeva commented on addon/mixins/flexberry-objectlistview-route.js
>            this.transitionTo(editFormRoute, recordId, transitionOptions);
Пробелы

2023-04-04 07:41 UTC, pepelyaeva commented on addon/mixins/flexberry-objectlistview-route.js
> +                this.controller.rejectError(errorData, this.get('i18n').t('forms.edit-form.save-failed-message'));
Пробелы

2023-04-04 07:41 UTC, pepelyaeva commented on addon/styles/themes/blue-sky/collections/table.overrides
Отменить изменения

2023-04-04 07:41 UTC, pepelyaeva commented on addon/styles/themes/blue-sky/modules/dropdown.overrides
Отменить изменения

2023-04-04 07:41 UTC, pepelyaeva commented on app/templates/components/modal-dialog.hbs
Все замечания линтера нужно поправить

2023-04-04 07:41 UTC, pepelyaeva commented on app/templates/editrecord-dialog.hbs
Все замечания линтера нужно поправить

2023-04-04 07:41 UTC, pepelyaeva commented on tests/dummy/app/controllers/components-examples/flexberry-objectlistview/settings-example.js
> -
Почему это удалено?

2023-04-04 07:45 UTC, pepelyaeva commented on addon/components/olv-toolbar.js
> +        const useSidePageMode = false;
Надо вернуть как было

2023-04-18 11:41 UTC, pepelyaeva commented on addon/mixins/edit-in-modal-open.js
> +  openCreateModalDialog(modelController, editFormRoute) {
Сюда не надо тоже `useSidePageMode` передавать?

2023-04-18 12:18 UTC, DubrovinPavel approved these changes

2023-04-19 05:44 UTC, pepelyaeva approved these changes

2023-04-19 05:46 UTC, merged